name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      
      - name: Download the github Repostiry 
        run: git clone "https://github.com/issacjohn/GithubActionsTest.git"
      - name: Execute the Repostiry
        run: |
          cd GithubActionsTest
          python3 print.py
        


